#include "app_lqr.h"

#include <math.h>

/* Generated by tools/lqr_gain.py for Ts=0.01 s, tau_xy=0.12 s,
 * tau_yaw=0.10 s, Qxy=diag(25,1), Qyaw=diag(16,1), R=1.
 * These are nominal model values, not identified robot parameters. */
#define LQR_XY_POSITION_GAIN 4.83842329f
#define LQR_XY_VELOCITY_GAIN 0.75554133f
#define LQR_YAW_POSITION_GAIN 3.86770058f
#define LQR_YAW_VELOCITY_GAIN 0.63758806f

static float clamp(float value, float limit)
{
    if (value > limit) return limit;
    if (value < -limit) return -limit;
    return value;
}

float AppLqr_WrapRadians(float angle)
{
    const float pi = 3.14159265358979323846f;
    while (angle >= pi) angle -= 2.0f * pi;
    while (angle < -pi) angle += 2.0f * pi;
    return angle;
}

AppLqrOutput AppLqr_Calculate(const AppLqrState *state,
                              const AppLqrReference *reference,
                              float translation_limit_m_s)
{
    AppLqrOutput out = {0.0f, 0.0f, 0.0f};
    float norm;
    if ((state == 0) || (reference == 0) ||
        !isfinite(state->x_m) || !isfinite(state->y_m) ||
        !isfinite(state->yaw_rad) || !isfinite(state->vx_m_s) ||
        !isfinite(state->vy_m_s) || !isfinite(state->wz_rad_s) ||
        !isfinite(reference->x_m) || !isfinite(reference->y_m) ||
        !isfinite(reference->yaw_rad) || !isfinite(reference->vx_m_s) ||
        !isfinite(reference->vy_m_s) || !isfinite(reference->wz_rad_s)) return out;

    out.vx_m_s = reference->vx_m_s -
        LQR_XY_VELOCITY_GAIN * (state->vx_m_s - reference->vx_m_s);
    out.vy_m_s = reference->vy_m_s -
        LQR_XY_VELOCITY_GAIN * (state->vy_m_s - reference->vy_m_s);
    if (reference->track_x)
        out.vx_m_s -= LQR_XY_POSITION_GAIN * (state->x_m - reference->x_m);
    if (reference->track_y)
        out.vy_m_s -= LQR_XY_POSITION_GAIN * (state->y_m - reference->y_m);
    out.wz_rad_s = reference->wz_rad_s -
        LQR_YAW_VELOCITY_GAIN * (state->wz_rad_s - reference->wz_rad_s);
    if (reference->track_yaw)
        out.wz_rad_s -= LQR_YAW_POSITION_GAIN *
            AppLqr_WrapRadians(state->yaw_rad - reference->yaw_rad);

    translation_limit_m_s = clamp(translation_limit_m_s, APP_LQR_VELOCITY_LIMIT_M_S);
    if (translation_limit_m_s < 0.0f) translation_limit_m_s = -translation_limit_m_s;
    norm = sqrtf(out.vx_m_s * out.vx_m_s + out.vy_m_s * out.vy_m_s);
    if ((norm > translation_limit_m_s) && (norm > 0.0f)) {
        out.vx_m_s *= translation_limit_m_s / norm;
        out.vy_m_s *= translation_limit_m_s / norm;
    }
    out.wz_rad_s = clamp(out.wz_rad_s, APP_LQR_YAW_RATE_LIMIT_RAD_S);
    return out;
}

AppLqrOutput AppLqr_LimitOmni(AppLqrOutput command, float yaw_rad,
                              float wheel_limit_m_s, float rotation_radius_m,
                              float forward_to_left, float left_to_forward)
{
    float cy = cosf(yaw_rad);
    float sy = sinf(yaw_rad);
    float forward = command.vx_m_s * cy + command.vy_m_s * sy;
    float left = -command.vx_m_s * sy + command.vy_m_s * cy;
    float corrected_forward = forward + left * left_to_forward;
    float corrected_left = left + forward * forward_to_left;
    float demand = fabsf(corrected_forward) + fabsf(corrected_left) +
                   fabsf(rotation_radius_m * command.wz_rad_s);
    if ((wheel_limit_m_s > 0.0f) && (demand > wheel_limit_m_s)) {
        float scale = wheel_limit_m_s / demand;
        command.vx_m_s *= scale;
        command.vy_m_s *= scale;
        command.wz_rad_s *= scale;
    }
    return command;
}

void AppLqr_ModelStep(float *position, float *velocity,
                      float command, float period_s, float tau_s)
{
    float decay;
    float old_velocity;
    if ((position == 0) || (velocity == 0) ||
        !(period_s > 0.0f) || !(tau_s > 0.0f)) return;
    decay = expf(-period_s / tau_s);
    old_velocity = *velocity;
    *position += tau_s * (1.0f - decay) * old_velocity +
                 (period_s - tau_s * (1.0f - decay)) * command;
    *velocity = decay * old_velocity + (1.0f - decay) * command;
}
